openapi: 3.1.0
info:
  title: Sales Order API
  version: 1.0.0
  description: API for managing sales orders.
servers:
  - url: YOUR_SERVER_URL_HERE
paths:
  /orders:
    get:
      summary: Retrieve a list of sales orders.
      responses:
        '200':
          description: A list of sales orders.
          content:
            application/json:
              schema:
                type: object
                properties:
                  orders:
                    type: array
                    items:
                      $ref: '#/components/schemas/Order'

    post:
      summary: Create a new sales order.
      requestBody:
        description: Sales order data to create.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '201':
          description: Sales order created successfully.

components:
  schemas:
    Order:
      type: object
      properties:
        CreatedByUser:
          type: string
          example: SERGEY
        CreationDate:
          type: string
          example: 3/18/2021
        DistributionChannel:
          type: string
          example: 01
        LastChangeDate:
          type: string
          example: ""
        OrganizationDivision:
          type: string
          example: ""
        OverallTotalDeliveryStatus:
          type: string
          example: SCHEDULED
        PricingDate:
          type: string
          example: 3/18/2021
        RequestedDeliveryDate:
          type: string
          example: 6/10/2021
        SalesDistrict:
          type: string
          example: ""
        SalesGroup:
          type: string
          example: ""
        SalesOffice:
          type: string
          example: ""
        SalesOrder:
          type: string
          example: 9000000232
        SalesOrderDate:
          type: string
          example: 3/15/2021
        SalesOrderType:
          type: string
          example: ZOR
        SalesOrganization:
          type: string
          example: 2000
        ShippingCondition:
          type: string
          example: ""
        SoldToParty:
          type: string
          example: 1003768
        TotalNetAmount:
          type: string
          example: 1356.08
        TransactionCurrency:
          type: string
          example: EUR